//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asuat
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SelectProduct = new HashSet<SelectProduct>();
        }
    
        public int IDProduct { get; set; }
        public byte[] ImgProduct { get; set; }
        public string NameProduct { get; set; }
        public int PledgePrice { get; set; }
        public int PriceProduct { get; set; }
        public bool Rent { get; set; }
        public string Check { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<System.DateTime> StartRent { get; set; }
        public Nullable<System.DateTime> EndRent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelectProduct> SelectProduct { get; set; }
    }
}
